# Generated by Django 5.0.1 on 2024-01-08 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userfile_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCropProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('process', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='process', max_length=16)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userfile')),
            ],
        ),
    ]
